### ISSUE TITLE
Problem with layout of multiple boxes in a sequence diagram

### ISSUE THREAD

**Issue by zoophag** [gobravedave/Enterprise-Architect#8]
If you define more than 1 box in a sequence diagram, then the graphical layout of the boxes is wrong (the boxes overlap).

Are you planning to add also support for component diagrams in near future? Would be nice to have a discussion here or over another channel. Thanks and br, Klaus

**Comment by gobravedave** [comment]
Hi @zoophag 
I have now fixed multiple box formatting..

also.. I am in the process of scripting C4 model exchanges.. which will include class and component diagrams..
